server {
    listen 80 default_server reuseport;
    listen [::]:80 default_server reuseport;

    listen 443 ssl default_server reuseport;
    listen [::]:443 ssl default_server reuseport;

    listen 443 quic default_server reuseport;
    listen [::]:443 quic default_server reuseport;

    server_name _;

    access_log off;

    ssl_reject_handshake on;
    return 444;
}
