name: Docker Build

on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build Testing
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and cache
        uses: docker/build-push-action@v2
        with:
          target: builder
          platforms: linux/amd64
          cache-to: type=gha, mode=max
          outputs: type=cacheonly
