name: Docker Publish

on:
  release:
    types:
      - published

env:
  USERNAME: akafeng
  REPOSITORY: nginx
  GITHUB_PACKAGE_REGISTRY: docker.pkg.github.com

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Process Version
        id: version
        uses: ncipollo/semantic-version-action@v1

      - name: Docker Login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ${{ env.GITHUB_PACKAGE_REGISTRY }} -u ${{ env.USERNAME }} --password-stdin
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ env.USERNAME }} --password-stdin

      - name: Docker Build
        env:
          STAGE_CACHE: ${{ env.GITHUB_PACKAGE_REGISTRY }}/${{ github.repository }}/${{ env.REPOSITORY }}:stage
          MINOR_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
          PATCH_TAG: ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}.${{ steps.version.outputs.patch }}
        run: |
          docker pull ${{ env.STAGE_CACHE }} || true
          docker build \
            --cache-from=${{ env.STAGE_CACHE }} \
            --tag=${{ env.MINOR_TAG }} \
            --tag=${{ env.PATCH_TAG }} \
            .

      - name: Create Latest Tag
        if: contains(github.ref, env.LATEST_VERSION)
        run: |
          docker tag ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.tag }} ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.major }}
          docker tag ${{ env.USERNAME }}/${{ env.REPOSITORY }}:${{ steps.version.outputs.tag }} ${{ env.USERNAME }}/${{ env.REPOSITORY }}:latest

      - name: Docker Publish
        run: docker push --all-tags ${{ env.USERNAME }}/${{ env.REPOSITORY }}
